### ISSUE TITLE
graphql-relay 3.2.0 breaks 

### ISSUE THREAD

**Issue by qmorek** [ciscorn/starlette-graphene3#26] opened 2022-04-19 10:50 UTC
There is some problem with starlette-graphene3 dependencies
I was using it with https://pypi.org/project/graphql-relay/3.1.5/
and in the meantime they released:
https://pypi.org/project/graphql-relay/3.2.0/
and after [starlette-graphene3](https://github.com/ciscorn/starlette-graphene3) installation from scratch I get 
ImportError: cannot import name 'resolve_thunk' from 'graphql' (/usr/local/lib/python3.8/dist-packages/graphql/init.py)

**Comment by vamshiaruru-virgodesigns** [comment] 2022-04-25 06:50
I also have the same error.  I am currently explicitly installing  3.1.5 to get around it.

**Comment by erikwrede** [comment] 2022-05-02 16:39
Graphene requires `graphql-core~=3.1.2`, but `graphql-relay~=3.2.0` requires `graphql-core>=3.2.0`. Minor versions of the python GQL libraries include breaking changes
(`resolve_thunk`: https://github.com/graphql-python/graphql-relay-py/commit/4c69f4f0b07a167016b3494005381f183cec10a6)
. See https://github.com/graphql-python/graphql-core:

> Note that for various reasons, GraphQL-core does not use SemVer like GraphQL.js. Increases in the major version of GraphQL.js are reflected in the minor version of GraphQL-core instead. This means there can be breaking changes in the API when the minor version changes, and only patch releases are fully backward compatible. Therefore, we recommend something like =~ 3.2.0 as version specifier when including GraphQL-core as a dependency.

I think this is a `graphene` issue causing the version conflict, not an issue with this library.

**Comment by ddelange** [comment] 2022-05-30 13:53
Noting here that pinning `graphql-core<3.2` as hotfix is not an option for us, as that is a direct incompatibility with any `gql` v3:

```console
$ pipgrip -vv starlette-graphene3 'graphql-core<3.2' gql~=3.3 graphene~=3.1
Error: Because no versions of gql match >3.3.0,<4.0
 and gql (3.3.0) depends on graphql-core (<3.3,>=3.2), gql (>=3.3.0,<4.0) requires graphql-core (<3.3,>=3.2).
So, because root depends on both graphql-core (<3.2) and gql (~=3.3), version solving failed.
```

**Comment by flipbit03** [comment] 2022-05-30 22:48
@erikwrede we meet again :-) My team is looking forward to trying to fix this for Graphene 3.1 (we are getting the `format_error` thing here).

**Comment by erikwrede** [comment] 2022-05-31 15:32
@johhnry as a quick fix, try adding out the branch of #29 to your requirements instead of this repo. Pip will build the repo from source. If you encounter any issues, let us know!

**Comment by johhnry** [comment] 2022-05-31 15:42
@erikwrede Thanks for the quick answer

The issue is that I am also using [`graphene-mongo`](https://github.com/graphql-python/graphene-mongo) which requires `graphene (3.0b7)`

There's a pull request on that repo switching to 3.0 but it's not merged now: https://github.com/graphql-python/graphene-mongo/pull/191/files

**Comment by erikwrede** [comment] 2022-05-31 15:51
Then you need to pin relay to 3.1.5 until mongo and this library merge the requests, or use that same method on the mongo PR. A bit hacky, but it should do the job until the respective maintainers push new releases. 
Keep in mind that building from the source without using specific tags for reference can lead to unwanted upstream changes leaking into production in case a repo is hijacked. I'd recommend you to fork all the repos you're building from source to prevent that.

**Comment by ddelange** [comment] 2022-05-31 15:51
you could try pinning `graphql-core==3.1.*` and use the existing published version of starlette-graphene3 (which should've had such a pin in hindsight)

```py
$ pipgrip --tree --pre graphene-mongo==0.2.14 starlette-graphene3 gql graphql-core==3.1.*
graphene-mongo==0.2.14 (0.2.14)
├── graphene==3.0b7 (3.0b7)
│   ├── aniso8601<9,>=8 (8.1.1)
│   ├── graphql-core<4,>=3.1.2 (3.2.0rc5)
│   └── graphql-relay<4,>=3.0 (3.1.5)
│       └── graphql-core<3.2,>=3.1 (3.2.0rc5)
├── iso8601>=0.1.12 (1.0.2)
├── mongoengine>=0.23.0 (0.24.1)
│   └── pymongo<5.0,>=3.4 (4.1.1)
├── promise==2.3 (2.3)
│   └── six (1.16.0)
└── singledispatch>=3.4.0.3 (3.7.0)
    └── six (1.16.0)
starlette-graphene3 (0.5.1)
├── graphene>=3.0b6 (3.0b7)
│   ├── aniso8601<9,>=8 (8.1.1)
│   ├── graphql-core<4,>=3.1.2 (3.2.0rc5)
│   └── graphql-relay<4,>=3.0 (3.1.5)
│       └── graphql-core<3.2,>=3.1 (3.2.0rc5)
└── starlette>=0.14.1 (0.20.1)
    └── anyio<5,>=3.4.0 (3.6.1)
        ├── idna>=2.8 (3.3)
        └── sniffio>=1.1 (1.2.0)
gql (3.0.0rc0)
├── graphql-core<3.2,>=3.1.5 (3.2.0rc5)
└── yarl<2.0,>=1.6 (1.7.2)
    ├── idna>=2.0 (3.3)
    └── multidict>=4.0 (6.0.2)
graphql-core==3.1.* (3.2.0rc5)
```

**Comment by ddelange** [comment] 2022-06-01 08:40
@johhnry I pushed changes that will allow `graphene>=3.0b6` again

**Comment by johhnry** [comment] 2022-06-01 12:50
@ddelange Thanks a lot I'll try that then!

**Closed** 2022-06-01 13:06 UTC
